// Generated by CoffeeScript 1.9.1
var LintWarning, eol_eof;

LintWarning = require('../warning/lint-warning');

eol_eof = require('./common/eol-eof');

module.exports = function(inf, cb) {
  var err;
  try {
    eol_eof(inf);
  } catch (_error) {
    err = _error;
    console.log('err', err.stack);
    inf.res.errors.push(new LintError(inf, err));
  }
  return cb();
};
