// Generated by CoffeeScript 1.9.1
var jade_compiler, rule_parser;

jade_compiler = require('../compiler/jade-html');

rule_parser = require('./rule/_parser');

module.exports = function(inf, cb) {
  inf.sourceMap = [];
  inf.includeSources = {};
  return jade_compiler(inf, function() {
    inf.compiledJade = inf.res.compiled;
    delete inf.res.compiled;
    if (inf.res.errors.length) {
      return cb();
    }
    return rule_parser(inf, 'jade', cb, function(cfg) {
      return cb();
    });
  });
};
