// Generated by CoffeeScript 1.9.1
var rule_parser;

rule_parser = require('./rule/_parser');

module.exports = function(inf, cb) {
  return rule_parser(inf, 'sass', cb, function(cfg) {
    return cb();
  });
};
