// Generated by CoffeeScript 1.9.1
module.exports = function(inf, source_type, msg_factory, title, lines) {
  var desc, last, last_count, pos;
  if (inf.source.substr(last = inf.source.length - 1) !== '\n') {
    desc = 'Missing enter character at end of file';
    pos = [lines.length - 1, lines[lines.length - 1].length];
    return msg_factory(pos, desc, title);
  } else {
    last_count = 1;
    while (inf.source.substr(last - last_count, 1) === '\n') {
      last_count += 1;
    }
    if (last_count > 1) {
      desc = 'Unnecessary empty line' + (last_count > 1 ? 's' : '') + ' at end of file';
      pos = [lines.length - last_count, 0];
      return msg_factory(pos, desc, title);
    }
  }
};
