// Generated by CoffeeScript 1.9.3
module.exports.source = function(msg_factory, source) {
  var desc, last, last_count, lines;
  if (source.substr(last = source.length - 1) !== '\n') {
    desc = 'Missing enter character at end of file';
    lines = source.split('\n');
    return msg_factory(desc, lines.length - 1, lines[lines.length - 1].length);
  } else {
    last_count = 1;
    while (source.substr(last - last_count, 1) === '\n') {
      last_count += 1;
    }
    if (last_count > 1) {
      desc = 'Unnecessary empty line' + (last_count > 1 ? 's' : '') + ' at end of file';
      return msg_factory(desc, source.split('\n').length - last_count, 0);
    }
  }
};
