// Generated by CoffeeScript 1.9.1
var parser;

parser = require('../../jade-nodes-parser');

module.exports.map = function(msg_factory, map) {
  var desc, i, len, line, node, ref;
  ref = parser.tagsWithNoAttrValue(map, 'img', 'src');
  for (i = 0, len = ref.length; i < len; i++) {
    node = ref[i];
    desc = '`img` tag needs `src` attribute with value';
    if (node.line != null) {
      line = node.line - 1;
    }
    msg_factory(desc, line, null, node.filename);
  }
};
