// Generated by CoffeeScript 1.9.2
var parser;

parser = require('../../jade-nodes-parser');

module.exports.map = function(msg_factory, map) {
  var desc, i, len, line, node, ref;
  ref = parser.tagsWithNoAttrValue(map, 'label', 'for');
  for (i = 0, len = ref.length; i < len; i++) {
    node = ref[i];
    desc = '`label` tag needs `for` attribute with value';
    if (node.line != null) {
      line = node.line - 1;
    }
    msg_factory(desc, line, null, node.filename);
  }
};
