// Generated by CoffeeScript 1.9.1
module.exports = function(inf, source_type, msg_factory, title) {
  var desc, i, len, name, node, pos, ref;
  ref = inf.jadeNodes;
  for (i = 0, len = ref.length; i < len; i++) {
    node = ref[i];
    if (typeof (name = node.name) === 'string' && name !== name.toLowerCase()) {
      desc = 'Tag name should be lowercase: `' + name + '`';
      pos = node.line != null ? node.line - 1 : null;
      msg_factory(pos, desc, title);
    }
  }
};
