// Generated by CoffeeScript 1.9.2
module.exports.map = function(msg_factory, map) {
  var desc, i, len, line, name, node;
  for (i = 0, len = map.length; i < len; i++) {
    node = map[i];
    if (typeof (name = node.name) === 'string' && name !== name.toLowerCase()) {
      desc = 'Tag name should be lowercase: `' + name + '`';
      if (node.line != null) {
        line = node.line - 1;
      }
      msg_factory(desc, line, null, node.filename);
    }
  }
};
