// Generated by CoffeeScript 1.9.2
module.exports.source = function(msg_factory, source, rule_value) {
  var desc, i, j, len, line, maxlen, ref;
  maxlen = rule_value;
  if (maxlen === true) {
    maxlen = 80;
  } else {
    maxlen = parseInt(maxlen, 10);
  }
  if (!(maxlen > 0)) {
    return;
  }
  ref = source.split('\n');
  for (i = j = 0, len = ref.length; j < len; i = ++j) {
    line = ref[i];
    if (!(line.length > maxlen)) {
      continue;
    }
    desc = 'Line length exceeds allowed maximum of ' + maxlen + ' characters';
    msg_factory(desc, i, maxlen);
  }
};
