// Generated by CoffeeScript 1.9.1
module.exports.source = function(msg_factory, source) {
  var desc, i, idx, j, len, line, ref, trimmed;
  ref = source.split('\n');
  for (i = j = 0, len = ref.length; j < len; i = ++j) {
    line = ref[i];
    if ((!(trimmed = line.trim())) && line) {
      desc = 'Line contains white spaces only';
      msg_factory(desc, i, 0);
    } else if ((idx = line.indexOf(trimmed) + trimmed.length) < line.length) {
      desc = 'Line has trailing white space';
      msg_factory(desc, i, idx);
    }
  }
};
