// Generated by CoffeeScript 1.9.1
module.exports = function(inf, source_type, msg_factory, title, lines) {
  var desc, i, idx, j, len, line, trimmed;
  for (i = j = 0, len = lines.length; j < len; i = ++j) {
    line = lines[i];
    if ((!(trimmed = line.trim())) && line) {
      desc = 'Line contains white spaces only';
      msg_factory([i, 0], desc, title);
    } else if ((idx = line.indexOf(trimmed) + trimmed.length) < line.length) {
      desc = 'Line has trailing white space';
      msg_factory([i, idx], desc, title);
    }
  }
};
