// Generated by CoffeeScript 1.9.1
var LintError;

LintError = require('../../error/lint-error');

module.exports = function(inf, source_type, msg_factory, title, lines) {
  var desc, pos;
  if (-1 < (pos = inf.source.indexOf('\r'))) {
    desc = 'CR (\\r) character found';
    pos = LintError.posByIndex(lines, pos);
    return msg_factory(pos, desc, title);
  }
};
