// Generated by CoffeeScript 1.9.1
module.exports.source = function(msg_factory, source) {
  var col, desc, line, pos, ref;
  if (-1 < (pos = source.indexOf('\r'))) {
    desc = 'CR (\\r) character found';
    ref = msg_factory["class"].posByIndex(source, pos), line = ref[0], col = ref[1];
    return msg_factory(desc, line, col);
  }
};
