// Generated by CoffeeScript 1.9.1
module.exports = function(err, _line, description, title) {
  var _column, column, from, i, j, len, line, line_literal, parsed_error, ref, ref1, ref2, ref3, source_lines;
  if (Array.isArray(_line)) {
    ref = _line, _line = ref[0], _column = ref[1];
  }
  parsed_error = {
    kscFileError: true,
    title: title || (err != null ? (ref1 = err.constructor) != null ? ref1.name : void 0 : void 0) || 'Error'
  };
  if (inf.file) {
    parsed_error.file = inf.file;
  }
  if (description) {
    parsed_error.description = description;
  }
  if (String(_line).indexOf('.') === -1 && (!isNaN(line = parseInt(_line, 10))) && line >= 0) {
    parsed_error.line = line;
    from = Math.max(0, line - 5);
    if ((ref2 = (source_lines = (ref3 = inf.source) != null ? ref3.split('\n').slice(from, +(line + 5) + 1 || 9e9) : void 0)) != null ? ref2.length : void 0) {
      for (i = j = 0, len = source_lines.length; j < len; i = ++j) {
        line_literal = source_lines[i];
        (parsed_error.sourceLines != null ? parsed_error.sourceLines : parsed_error.sourceLines = {})[from + i] = line_literal;
      }
    }
  }
  if (String(_column).indexOf('.') === -1 && (!isNaN(column = parseInt(_column, 10))) && column >= 0) {
    parsed_error.column = column;
  }
  return parsed_error;
};
