// Generated by CoffeeScript 1.9.2
var Issue, rule;

Issue = null;

rule = require('../../node_modules/htmllint/lib/rules/html-req-lang');

rule.lint = function(element, opts) {
  var ref, ref1;
  if (!(opts[this.name] && !(element != null ? (ref = element.attribs) != null ? (ref1 = ref.lang) != null ? ref1.value : void 0 : void 0 : void 0))) {
    return [];
  }
  if (Issue == null) {
    Issue = require('../../node_modules/htmllint/lib/issue');
  }
  return new Issue('E025', element.openLineCol);
};
