// Generated by CoffeeScript 1.9.1
var Jade, path,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Jade = require('jade');

path = require('path');

Jade.Parser.prototype._multicPatch_parseInclude = Jade.Parser.prototype.parseInclude;

Jade.Parser.prototype.parseInclude = function() {
  var ipath, ref, tok;
  if (Array.isArray((ref = this.options) != null ? ref.includes : void 0)) {
    tok = this.peek();
    ipath = path.resolve(this.resolvePath(tok.val.trim(), 'include'));
    if (indexOf.call(this.options.includes, ipath) < 0) {
      this.options.includes.push(ipath);
    }
  }
  return this._multicPatch_parseInclude();
};

Jade.Parser.prototype._multicPatch_parseExpr = Jade.Parser.prototype.parseExpr;

Jade.Parser.prototype.parseExpr = function() {
  var expr, ref, ref1;
  expr = this._multicPatch_parseExpr();
  if (Array.isArray((ref = this.options) != null ? ref.nodes : void 0)) {
    if ((ref1 = this.options) != null) {
      ref1.nodes.push(expr);
    }
  }
  return expr;
};
