// Generated by CoffeeScript 1.9.1
var MinificationError, minifier;

MinificationError = require('../error/minification-error');

minifier = require('clean-css');

module.exports = function(inf, cb) {
  var err, i, j, len, len1, ref, ref1, res, warn;
  try {
    res = (new minifier({})).minify(inf.source);
    ref = res.errors || [];
    for (i = 0, len = ref.length; i < len; i++) {
      err = ref[i];
      inf.res.errors.push(new MinificationError(inf, err));
    }
    ref1 = res.warnings || [];
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      warn = ref1[j];
      inf.res.errors.push(new MinificationError(inf, warn));
    }
    inf.res.minified = res != null ? res.styles : void 0;
  } catch (_error) {
    err = _error;
    inf.res.errors.push(new MinificationError(inf, err));
  }
  return cb();
};
