// Generated by CoffeeScript 1.9.1
var minifier;

minifier = require('clean-css');

module.exports = function(inf, cb) {
  var err, ref, ref1, ref2, ref3, res;
  try {
    res = (new minifier({})).minify(inf.source);
    if (res != null ? (ref = res.warnings) != null ? ref.length : void 0 : void 0) {
      (ref1 = inf.res.warnings).push.apply(ref1, res.warnings);
    }
    if (res != null ? (ref2 = res.errors) != null ? ref2.length : void 0 : void 0) {
      (ref3 = inf.res.errors).push.apply(ref3, res.errors);
    }
    inf.res.minified = res != null ? res.styles : void 0;
  } catch (_error) {
    err = _error;
    inf.res.errors.push(err);
  }
  return cb();
};
