// Generated by CoffeeScript 1.9.1
var MinificationError, minifier;

MinificationError = require('../error/minification-error');

minifier = require('minimize');

module.exports = function(inf, cb) {
  var err, minify_fn;
  try {
    minify_fn = new minifier({
      empty: true,
      cdata: true,
      comments: true,
      conditionals: true
    });
    minify_fn.parse(inf.source, function(err, minified) {
      if (err) {
        inf.res.errors.push(new MinificationError(inf, err));
      }
      inf.res.minified = minified;
      return cb();
    });
  } catch (_error) {
    err = _error;
    inf.res.errors.push(new MinificationError(inf, err));
  }
  return cb();
};
