// Generated by CoffeeScript 1.9.1
var MinificationError, UglifyJs;

MinificationError = require('../error/minification-error');

UglifyJs = require('uglify-js');

module.exports = function(inf, cb) {
  var err, pos;
  try {
    inf.res.minified = UglifyJs.minify(inf.source, {
      fromString: true
    }).code;
  } catch (_error) {
    err = _error;
    pos = MinificationError.parsePos(err.line, err.col, -1);
    inf.res.errors.push(new MinificationError(inf, err, pos));
  }
  return cb();
};
