// Generated by CoffeeScript 1.9.1
var minifier;

minifier = require('uglify-js');

module.exports = function(inf, cb) {
  var err, minified;
  try {
    minified = minifier.minify(inf.source, {
      fromString: true
    }).code;
    return cb(null, minified);
  } catch (_error) {
    err = _error;
    return cb(err);
  }
};
