// Generated by CoffeeScript 1.9.1
var minifier;

minifier = require('uglify-js');

module.exports = function(inf, cb) {
  var err, minified;
  minified = minifier.minify(inf.source, {
    fromString: true
  }).code;
  try {
    if (err) {
      inf.res.errors.push(err);
    }
    inf.res.minified = minified;
  } catch (_error) {
    err = _error;
    inf.res.errors.push(err);
  }
  return cb();
};
