// Generated by CoffeeScript 1.9.3
var js_map, k1, k2, v1, v2;

js_map = require('./js');

for (k1 in js_map) {
  v1 = js_map[k1];
  module.exports[k1] = {};
  for (k2 in v1) {
    v2 = v1[k2];
    module.exports[k1][k2] = v2;
  }
}

module.exports.mandatory_warnings.es6 = 'esnext';
