// Generated by CoffeeScript 1.9.1
module.exports = {
  errors: {
    unix_line_end: true,
    no_unsafe_attribute_characters: 0
  },
  mandatory_warnings: {
    html_lang_required: true,
    img_alt_required: true,
    img_src_required: true,
    label_for_required: true,
    lowercase_tag_names: true
  },
  enabled_warnings: {
    file_end_newline: true,
    indentation: 0,
    no_line_end_whitespace: true,
    no_non_breaking_space: 0,
    no_tabs: 0,
    quote_consistency: 0,
    no_comma_separated_attributes: 0
  },
  disabled_warnings: {
    max_line_length: true,
    no_implicit_attribute_value: 0
  }
};
