// Generated by CoffeeScript 1.9.3
module.exports = {
  errors: {
    unix_line_end: true
  },
  mandatory_warnings: {},
  enabled_warnings: {
    file_end_newline: true,
    no_line_end_whitespace: true,
    no_non_breaking_space: 0,
    no_tabs: 0
  },
  disabled_warnings: {
    max_line_length: true
  }
};
