// Generated by CoffeeScript 1.9.1
module.exports = {
  errors: {
    unix_line_end: true
  },
  mandatory_warnings: {
    no_overqualified_elements: 0,
    no_star_hack: 0,
    no_underscore_hack: 0,
    no_units_for_zero: 0,
    standard_property_required: 0
  },
  enabled_warnings: {
    file_end_newline: true,
    indentation: 0,
    line_end_whitespace: true,
    no_tabs: 0,
    braces_spacing: 0,
    no_id_selectors: 0,
    no_important_hack: 0,
    no_universal_selectors: 0,
    no_unqualified_attribute_selectors: 0,
    spacing_after_comma: 0
  },
  disabled_warnings: {
    max_line_length: true,
    no_outline_disabling: 0,
    no_qualified_headings: 0,
    shorthand_property_required: 0,
    unique_headings: 0
  }
};
