// Generated by CoffeeScript 1.9.1
var MinificationWarning, MulticError,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

MulticError = require('../multic-error');

MinificationWarning = (function(superClass) {
  extend(MinificationWarning, superClass);

  function MinificationWarning() {
    return MinificationWarning.__super__.constructor.apply(this, arguments);
  }

  return MinificationWarning;

})(MulticError);

module.exports = MinificationWarning;
