// Generated by CoffeeScript 1.9.2
var CoffeeScript, CompilationError;

CoffeeScript = require('coffee-script');

CompilationError = require('../error/compilation-error');

module.exports = function(inf, cb) {
  var desc, err, opts, pos, ref, ref1;
  try {
    opts = {
      bare: true
    };
    if (inf.options.file) {
      opts.filename = inf.options.file;
    }
    inf.res.compiled = CoffeeScript.compile(inf.source, opts);
  } catch (_error) {
    err = _error;
    desc = String(err).split('\n')[0].split(':').slice(4).join(':').trim();
    pos = CompilationError.parsePos((ref = err.location) != null ? ref.first_line : void 0, (ref1 = err.location) != null ? ref1.first_column : void 0);
    inf.res.errors.push(new CompilationError(inf, err, pos, desc));
  }
  return cb();
};
