// Generated by CoffeeScript 1.9.1
var compiler;

compiler = require('6to5');

module.exports = function(inf, cb) {
  var c, compiled, desc, err, l, line, line_n, parsed_opts, pos, ref, ref1, ref2, ref3;
  try {
    parsed_opts = {};
    if (inf.file) {
      parsed_opts.filename = inf.file;
    }
    compiled = (compiler.transform(inf.source, parsed_opts)).code;
    return cb(null, compiled);
  } catch (_error) {
    err = _error;
    desc = String(err).split('\n')[0].split(':').slice(2).join(':').trim();
    if (((l = (ref = err.loc) != null ? ref.line : void 0) != null) && ((c = (ref1 = err.loc) != null ? ref1.column : void 0) != null)) {
      if ((pos = desc.lastIndexOf(' (' + l + ':' + c + ')')) > -1) {
        desc = desc.substr(0, pos);
      }
    }
    if (!isNaN(Number(line_n = (ref2 = err.loc) != null ? ref2.line : void 0))) {
      line = line_n - 1;
    }
    pos = [line, (ref3 = err.loc) != null ? ref3.column : void 0];
    return cb(require('../error-parser')(inf, err, pos, desc));
  }
};
