// Generated by CoffeeScript 1.9.1
var compiler, error_parser;

compiler = require('ng-html2js');

error_parser = require('../error-parser');

module.exports = function(inf, cb) {
  var err;
  try {
    inf.res.compiled = compiler(inf.file, inf.source);
  } catch (_error) {
    err = _error;
    inf.res.errors.push(err);
  }
  return cb();
};
