// Generated by CoffeeScript 1.9.1
var CompilationError, ng_html2js;

CompilationError = require('../error/compilation-error');

ng_html2js = require('ng-html2js');

module.exports = function(inf, cb) {
  var err;
  try {
    inf.res.compiled = ng_html2js(inf.options.file, inf.source);
  } catch (_error) {
    err = _error;
    inf.res.errors.push(new CompilationError(inf, err));
  }
  return cb();
};
