// Generated by CoffeeScript 1.9.1
var compiler;

compiler = require('ng-html2js');

module.exports = function(inf, cb) {
  var compiled, err;
  try {
    compiled = compiler(inf.file, inf.source);
    return cb(null, compiled, null);
  } catch (_error) {
    err = _error;
    return cb(err);
  }
};
