// Generated by CoffeeScript 1.9.3
var html2js, jade2html;

jade2html = require('./jade-html');

html2js = require('./html-js');

module.exports = function(inf, cb) {
  return jade2html(inf, function() {
    if (inf.res.errors.length) {
      return cb();
    }
    inf.source = inf.res.compiled;
    return html2js(inf, cb);
  });
};
