// Generated by CoffeeScript 1.9.1
var compiler, error_parser, path;

compiler = require('node-sass');

error_parser = require('../error-parser');

path = require('path');

module.exports = function(inf, cb) {
  var err, pathes, stats;
  try {
    stats = {};
    pathes = [];
    if (inf.file) {
      pathes.push(path.dirname(inf.file) + '/');
    }
    return compiler.render({
      data: inf.source,
      includePaths: pathes,
      stats: stats,
      error: function(err) {
        inf.res.errors.push(err);
        return cb();
      },
      success: function(res) {
        var includes, ref, ref1, ref2;
        if ((ref = (includes = res != null ? (ref1 = res.stats) != null ? ref1.includedFiles : void 0 : void 0)) != null ? ref.length : void 0) {
          (ref2 = inf.res.includes).push.apply(ref2, includes);
        }
        inf.res.compiled = res.css;
        return cb();
      }
    });
  } catch (_error) {
    err = _error;
    inf.res.errors.push(err);
    return cb();
  }
};
