// Generated by CoffeeScript 1.9.1
var compiler, path;

compiler = require('node-sass');

path = require('path');

module.exports = function(inf, cb) {
  var err, error, pathes, stats;
  error = function(err) {
    return cb(err);
  };
  try {
    stats = {};
    pathes = [];
    if (inf.file) {
      pathes.push(path.dirname(inf.file) + '/');
    }
    return compiler.render({
      data: inf.source,
      error: error,
      includePaths: pathes,
      stats: stats,
      success: function(res) {
        var includes, ref, ref1;
        if (!((ref = (includes = res != null ? (ref1 = res.stats) != null ? ref1.includedFiles : void 0 : void 0)) != null ? ref.length : void 0)) {
          includes = null;
        }
        return cb(null, res.css, includes);
      }
    });
  } catch (_error) {
    err = _error;
    return error(err);
  }
};
